### ISSUE TITLE
Update liquibase 3.4.2 to 3.5.1 Failed

### ISSUE THREAD

**Issue by baptistejammet** [DSI-Ville-Noumea/puppet-liquibase#18]
[puppet_run.txt](https://github.com/DSI-Ville-Noumea/puppet-liquibase/files/290166/puppet_run.txt)

`2016-05-31 11:08:50 +1100 /Stage[main]/Liquibase::Install/File[/opt/apps/liquibase/liquibase-3.4.2]/ensure (err): change from directory to absent failed: Could not back up /opt/apps/liquibase/liquibase-3.4.2/lib/jtds-1.3.1.jar: Error 400 on SERVER: Got passed new contents for sum {md5}a0fe47907babf3bdb555e0b6f9dedd24`

`rm  /opt/apps/liquibase/ -rf`

Puppet run again; successful.

**Comment by mbarre** [comment]
Which version of puppet ?

**Comment by baptistejammet** [comment]
#4 pull request
